twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: /teleop/cmd_vel
        timeout: 0.5
        priority: 100
      nav2:
        topic: /nav2/cmd_vel
        timeout: 0.5
        priority: 50
      autonomous:
        topic: /brain/cmd_vel
        timeout: 0.5
        priority: 10
