twist_mux:
  ros__parameters:
    topics:

      - name: teleop
        topic: /teleop/cmd_vel
        timeout: 0.5
        priority: 100.0

      - name: nav2
        topic: /nav2/cmd_vel
        timeout: 0.5
        priority: 50.0

      - name: autonomous
        topic: /brain/cmd_vel
        timeout: 0.5
        priority: 10.0